# Generated by Django 4.0.6 on 2022-08-12 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_num', models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third')], max_length=10, verbose_name='Поле')),
                ('schedule', models.DateTimeField(verbose_name='Дата и время')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Статус')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_corts', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Баскетбольная площадка',
                'verbose_name_plural': 'Баскетбольные площадки',
                'db_table': 'court',
            },
        ),
    ]
