# Generated by Django 4.0.6 on 2022-08-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='is_booked',
            field=models.BooleanField(default=False, verbose_name='Забронирован'),
        ),
    ]
