# Generated by Django 4.0.6 on 2022-08-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_myuser_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
