# Generated by Django 4.0.6 on 2022-08-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинги'},
        ),
        migrations.AlterField(
            model_name='team',
            name='player1',
            field=models.CharField(max_length=50, verbose_name='Игрок 1'),
        ),
        migrations.AlterField(
            model_name='team',
            name='player2',
            field=models.CharField(max_length=50, verbose_name='Игрок 2'),
        ),
        migrations.AlterField(
            model_name='team',
            name='player3',
            field=models.CharField(max_length=50, verbose_name='Игрок 3'),
        ),
        migrations.AlterField(
            model_name='team',
            name='player4',
            field=models.CharField(max_length=50, verbose_name='Игрок 4'),
        ),
        migrations.AlterField(
            model_name='team',
            name='player5',
            field=models.CharField(max_length=50, verbose_name='Игрок 5'),
        ),
        migrations.AlterField(
            model_name='team',
            name='slogan',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Девиз'),
        ),
    ]
