# Generated by Django 4.0.6 on 2022-08-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_rating_options_alter_team_player1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='seller',
            new_name='author',
        ),
    ]
