# Generated by Django 4.0.6 on 2022-08-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_rename_seller_rating_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='vehicle',
            new_name='team',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='favourite',
        ),
    ]
